### ISSUE TITLE
cloning does not get `src/ecos@...` directory

### ISSUE THREAD

**Issue by mmaechler** [bnaras/ECOSolveR#6]
Giving context, too:  

The next version of the `Matrix` package (developed on R-forge: [R-forge/matrix](https://r-forge.r-project.org/projects/matrix/),
typically installable via   `install.packages("Matrix", repos="http://R-Forge.R-project.org")`
produces  "diagonalMatrix" objects more commonly than previously, and so checking your CVXR package fails its checks with that "next version" Matrix package.
The first example that fails,   `example(domain)`    actually does fail when eventually calling  `ECOSolveR::csolve(.)`, hence the issue here, as I (as `Matrix author) can easily fix your setup code to make it work again.  Here's the end of `example(domain)` when using Matrix 1.3-0 (from R-forge):

```r
> result <- solve(Problem(Minimize(norm2(A - A0)), dom))
Error in ECOSolveR::ECOS_csolve(c = data[[C_KEY]], G = data[[G_KEY]],  :
  G is required to be of class dgCMatrix or matrix or simple_triplet_matrix
  Calls: solve ... reduction_solve_via_data -> solve_via_data -> solve_via_data -> <Anonymous>
```
So I've forked `ECOSolveR` and think I fixed up the R code, but then wanted to test, and for that to build and check the package.
I needed too  long (> 20 minutes) to find that the *reason* for why even my build failed was that actually, cloning this github repos does *not* produce what I see on the github web interface, but instead of your 
```
 	src/ecos @ 2954b2a
```
which I see (and can browse) on the web interface, I get an **empty**  `src/ecos/` directory,
see here :   
```{bash}
$ (cd ECOSolveR/src ; tree)
.
├── ecos
├── ecos-2954b2a-changes
│   ├── ecos_bb
│   │   ├── ecos_bb.c
│   │   └── ecos_bb_preproc.c
│   ├── ecos-unix.mk
│   ├── ecos-win.mk
│   ├── include
│   │   ├── ecos_bb.h
│   │   └── glblopts.h
│   ├── Makefile
│   └── README.txt
├── ecosolve.c
├── ecosolver_init.c
├── ecos.ts
├── Makevars
└── Makevars.win
```
I do notice that for you this is a "github - link" to the real  `ecos` library sources,
and the same is true for [`src/` of my fork of your repos](https://github.com/mmaechler/ECOSolveR/tree/master/src);  but when (on Fedora 30 Linux, in a bash)
```
git clone https://github.com/mmaechler/ECOSolveR/tree/master/src
```
I get the above which I cannot really use.

What's the trick I need to apply ??

**Comment by wenjie2wang** [comment]
@mmaechler, I happened to see this issue as one of your followers on GitHub.  It seems that the "empty" `src/ecos @ 2954b2a` is a git submodule.

You may try
```
git clone --recurse-submodules https://github.com/bnaras/ECOSolveR.git
```
to clone the repository once again with the submodule.

Or initialize and clone the submodule in your "git-cloned" repository as follows:
```
git submodule update --init --recursive
```

Hope it helps.

**Comment by bnaras** [comment]
Just saw this now. Yes @wenjie2wang is right: you need the submodule.

**Comment by mmaechler** [comment]
Thanks a lot; I used your `git submodule update ....`  which worked flawlessly.  @bnaras : Maybe add the   `--recurse-submodules `  somewhere prominently on "the landing page" .. as reference for others (and possibly my future self ;-)
