### ISSUE TITLE
Errors when installing ECOSolveR on MacOS Big Sur 11.04

### ISSUE THREAD

**Issue by scentorrino** [bnaras/ECOSolveR#8]
Hello, 

I am having quite some issues installing your package on MacOS. 

1) It seems like that, in spite of the changes you have pulled, the install cannot correctly locate the R headers. This is a problem especially when installing the LDL and AMD packages (the definitions in the Makevars file aren't transferred to the Makefiles in either package)

2) After some manipulations with the file headers, I get a memory fragmentation error when trying to run your vignette (please see [ECOSolveRout.txt](https://github.com/bnaras/ECOSolveR/files/6651580/ECOSolveRout.txt). 

my sessionInfo()

R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin20.5.0 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
BLAS:   /opt/local/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.dylib
LAPACK: /opt/local/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.1.0

Any help would be appreciated. 

Regards, 

SC

**Comment by bnaras** [comment]
The package builds and installs correctly on all platforms as this shown [here](https://cran.r-project.org/web/checks/check_results_ECOSolveR.html).  The fact that your R installation cannot locate R headers suggests something wrong with your setup. That simply should not happen! Can't help without further details.

**Comment by scentorrino** [comment]
Hello, 

thanks for getting back to me. Ok, I seem to have a similar issue when installing the cubature package that you also maintain (I get an error "rcubature.h not found"). Other packages build just fine under my setup. 

I have run "R CMD config --all" on my terminal and I attach the output. If it can help, I have installed R from MacPorts. Please let me know if you need further details. 

Best,

SC

[config.txt](https://github.com/bnaras/ECOSolveR/files/6658261/config.txt)

**Comment by scentorrino** [comment]
Ok. Thanks for pointing out that my setup was flawed. The issue was a conflict between my R install and the content of the local file ~/.R/Makevars. After deleting ~/.R/Makevars, everything compiles properly. 

Best, 

SC
